'use client';
import {useMemo,useState} from 'react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,BarChart,Bar,CartesianGrid} from 'recharts';
import {Download,RefreshCw,Database,Plane,Activity,Clock3,ShieldCheck} from 'lucide-react';
import {indexSeries,routeIndex,leadElasticity,stats,quoteData} from '../lib/data';

export default function Dashboard(){
 const [route,setRoute]=useState('All routes'); const [lead,setLead]=useState('All'); const [query,setQuery]=useState('');
 const filtered=useMemo(()=>quoteData.filter(q=>(route==='All routes'||q.route===route)&&(lead==='All'||String(q.lead)===lead)&&(!query||q.airline.toLowerCase().includes(query.toLowerCase())||q.route.toLowerCase().includes(query.toLowerCase()))),[route,lead,query]);
 const exportCSV=()=>{const head='route,airline,lead_days,base,tax,fee,total,status,captured\n';const body=filtered.map(q=>`${q.route},${q.airline},${q.lead},${q.base},${q.tax},${q.fee},${q.total},${q.status},${q.captured}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([head+body],{type:'text/csv'}));a.download='airfare_quotes.csv';a.click()};
 return <div className="shell"><header className="topbar"><div className="brand"><div className="logo">A</div>Airfare Index India</div><div className="topnav"><span className="active">Dashboard</span><span>Data Explorer</span><span>Methodology</span><span>API</span></div><div className="status"><i className="dot"/>Pipeline healthy</div></header><main>
 <div className="hero"><div><div className="eyebrow">NSO / RBI augmentation prototype</div><h1>Real-time Airfare Price Index</h1><p>High-frequency view of domestic airfare movements across representative Indian city-pairs, designed around advance-purchase windows and total consumer-facing fare.</p></div><button className="select" onClick={()=>location.reload()}><RefreshCw size={14}/> Refresh snapshot</button></div>
 <div className="grid"><Metric icon={<Activity size={16}/>} label="Airfare Index" value={stats.index.toFixed(1)} delta="+2.8% vs last week"/><Metric icon={<Clock3 size={16}/>} label="Monthly movement" value={`+${stats.monthly}%`} delta="30-day change"/><Metric icon={<Database size={16}/>} label="Quotes processed" value={stats.quotes.toLocaleString()} delta="Daily ingestion target"/><Metric icon={<Plane size={16}/>} label="Routes covered" value={stats.routes} delta={`${stats.sources} source portals`}/></div>
 <div className="section sectiongrid"><section className="card"><div className="toolbar"><h2>Daily Airfare Price Index</h2><span className="badge">Base = 100</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={indexSeries}><CartesianGrid stroke="#20344c" strokeDasharray="3 3"/><XAxis dataKey="date" stroke="#71869d" fontSize={10}/><YAxis domain={['dataMin-2','dataMax+2']} stroke="#71869d" fontSize={10}/><Tooltip contentStyle={{background:'#0b1727',border:'1px solid #20344c',borderRadius:10}}/><Line type="monotone" dataKey="value" stroke="#5eead4" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div><div className="note">MVP series uses a deterministic demonstration dataset so the dashboard works immediately after deployment. The ingestion layer is intentionally separated from the index engine.</div></section>
 <section className="card"><div className="toolbar"><h2>Lead-time elasticity</h2><span className="badge">Avg total fare</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={leadElasticity}><XAxis dataKey="lead" stroke="#71869d" fontSize={10}/><YAxis stroke="#71869d" fontSize={10}/><Tooltip contentStyle={{background:'#0b1727',border:'1px solid #20344c',borderRadius:10}}/><Bar dataKey="avg" fill="#60a5fa" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section></div>
 <div className="section sectiongrid"><section className="card"><div className="toolbar"><h2>Route movement heatmap</h2><span className="badge">Weighted route index</span></div><div className="heat">{routeIndex.map((r,i)=><div key={r.route} className={`heatcell heat${Math.min(4,1+(i%4))}`}><b>{r.route}</b><small>{r.index} · <span className={r.change>=0?'up':'down'}>{r.change>=0?'+':''}{r.change}%</span></small></div>)}</div></section>
 <section className="card"><div className="toolbar"><h2>Methodology at a glance</h2><ShieldCheck size={18}/></div><p className="note" style={{fontSize:13}}>1. Capture comparable quotes by route, airline and advance window.</p><p className="note" style={{fontSize:13}}>2. Separate base fare, taxes, UDF and convenience fees.</p><p className="note" style={{fontSize:13}}>3. De-duplicate and remove abnormal observations.</p><p className="note" style={{fontSize:13}}>4. Apply fixed route weights and compute a price-relative index.</p><p className="note" style={{fontSize:13}}>5. Publish daily, weekly and monthly series through an API.</p></section></div>
 <section className="card section"><div className="toolbar"><h2>Quote explorer</h2><button className="select" onClick={exportCSV}><Download size={14}/> Export CSV</button></div><div className="toolbar"><div className="search"><input placeholder="Search route / airline" value={query} onChange={e=>setQuery(e.target.value)}/><select className="select" value={route} onChange={e=>setRoute(e.target.value)}><option>All routes</option>{routeIndex.map(r=><option key={r.route}>{r.route}</option>)}</select><select className="select" value={lead} onChange={e=>setLead(e.target.value)}><option>All</option>{[1,7,15,30,45].map(x=><option key={x}>{x}</option>)}</select></div><span className="badge">Showing {filtered.length} quotes</span></div><div className="tablewrap"><table className="table"><thead><tr><th>Route</th><th>Airline</th><th>Lead</th><th>Base</th><th>Tax</th><th>Fee</th><th>Total</th><th>Status</th></tr></thead><tbody>{filtered.slice(0,18).map((q,i)=><tr key={i}><td><b>{q.route}</b></td><td>{q.airline}</td><td>{q.lead}d</td><td>₹{q.base.toLocaleString()}</td><td>₹{q.tax.toLocaleString()}</td><td>₹{q.fee}</td><td><b>₹{q.total.toLocaleString()}</b></td><td><span className="pill">{q.status}</span></td></tr>)}</tbody></table></div></section>
 <div className="footer">Airfare Index India · Prototype for Problem Statement 26056 · Demo data is synthetic and clearly labelled for hackathon presentation.</div>
 </main></div>;
}
function Metric({icon,label,value,delta}:{icon:React.ReactNode,label:string,value:string|number,delta:string}){return <div className="card"><div style={{display:'flex',justifyContent:'space-between',color:'#8da3ba'}}>{icon}<span className="metric-label">{label}</span></div><div className="metric">{value}</div><div className="delta">{delta}</div></div>}
